name: Build launcher.exe

on:
  push:
    paths:
      - 'launcher.cpp'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH

      - name: Compile launcher.cpp
        run: g++ launcher.cpp -o launcher.exe

      - name: Upload launcher.exe
        uses: actions/upload-artifact@v3
        with:
          name: launcher-exe
          path: launcher.exe
